move dev dependencies to dependency-groups, separate jobs for linting and typing
- also: modernize tox config and remove default --installed for now

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -24,11 +24,6 @@ jobs:
             args: "--run-writes"
             extra: ",pandas"
             os: windows-latest
-          - name: linux-3.14-quick-typecheck-lint
-            python-version: "3.14"
-            args: "--skip-slow --exclude-raw"
-            extra: ",dev,pandas"
-            os: ubuntu-latest
           - name: linux-3.13-quick
             python-version: "3.13"
             args: "--skip-slow --exclude-raw"
@@ -59,7 +54,7 @@ jobs:
           echo "::group::Run git config --system core.longpaths true"
           git config --system core.longpaths true
           echo "::endgroup::"
-      - name: Checkout repo
+      - name: Checkout souce repo
         uses: actions/checkout@v4
       - name: Setup Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
@@ -70,8 +65,8 @@ jobs:
           echo "::group::Run python -m pip install --upgrade pip setuptools wheel"
           python -m pip install --upgrade pip setuptools wheel
           echo "::endgroup::"
-          echo "::group::Run pip install .[test,pretty${{ matrix.extra }}] mypy flake8"
-          pip install .[test,pretty${{ matrix.extra }}] mypy flake8
+          echo "::group::Run pip install .[pretty${{ matrix.extra }}] --group test"
+          pip install .[pretty${{ matrix.extra }}] --group test
           echo "::endgroup::"
       - name: Pip downgrade sqlalchemy to 1.0 version (if -sa1)
         if: ${{ contains(matrix.name, '-sa1') }}
@@ -91,24 +86,6 @@ jobs:
           echo "::endgroup::"
           [ $FAILED -eq 0 ] || echo "::warning::try-treedb.py failed with exit code $FAILED"
         shell: bash
-      - name: Run mypy (if -typecheck)
-        if: ${{ contains(matrix.name, '-typecheck') }}
-        run: |
-          echo "::group::Run mypy"
-          FAILED=0
-          python -m mypy || FAILED=$?
-          echo "::endgroup::"
-          [ $FAILED -eq 0 ] || echo "::warning::mypy failed with exit code $FAILED"
-        shell: bash
-      - name: Run lint-code.py (if -lint)
-        if: ${{ contains(matrix.name, '-lint') }}
-        run: |
-          echo "::group::Run lint-code.py --version"
-          echo "$(python lint-code.py --version)"
-          echo "::endgroup::"
-          echo "::group::Run lint-code.py"; FAILED=0; python lint-code.py || FAILED=$?; echo "::endgroup::"
-          [ $FAILED -eq 0 ] || echo "::warning::lint-code.py failed with exit code $FAILED"
-        shell: bash
       - name: Upload ${{ matrix.name }} artifacts
         uses: actions/upload-artifact@v4
         with:
@@ -118,3 +95,45 @@ jobs:
             treedb*.sqlite3
             treedb*.jsonl
             treedb*.csv
+  lint-code:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - python-version: "3.14"
+    steps:
+      - name: Checkout source repo
+        uses: actions/checkout@v4
+      - name: Setup Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Pip install --group lint
+        run: pip install --group lint
+      - name: Run lint-code.py
+        run: |
+          FAILED=0
+          python lint-code.py || FAILED=$?
+          [ $FAILED -eq 0 ] || echo "::warning::lint-code.py failed with exit code $FAILED"
+        shell: bash
+  typecheck-code:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - python-version: "3.14"
+    steps:
+      - name: Checkout source repo
+        uses: actions/checkout@v4
+      - name: Setup Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Pip install --group typing
+        run: pip install --group typing
+      - name: Run mypy
+        run: |
+          FAILED=0
+          python -m mypy || FAILED=$?
+          [ $FAILED -eq 0 ] || echo "::warning::mypy failed with exit code $FAILED"
+        shell: bash
