quote echo output

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -50,10 +50,10 @@ jobs:
         run: |
           echo "::group::Check HKLM:System\CurrentControlSet\Control\FileSystem.LongPathsEnabled"
           (Get-ItemProperty HKLM:System\CurrentControlSet\Control\FileSystem).LongPathsEnabled
-          echo ::endgroup::
+          echo "::endgroup::"
           echo "::group::Run git config --system core.longpaths true"
           git config --system core.longpaths true
-          echo ::endgroup::
+          echo "::endgroup::"
       - name: Checkout repo
         uses: actions/checkout@v2
       - name: Setup Python ${{ matrix.python-version }}
@@ -64,10 +64,10 @@ jobs:
         run: |
           echo "::group::Run python -m pip install --upgrade pip setuptools wheel"
           python -m pip install --upgrade pip setuptools wheel
-          echo ::endgroup::
+          echo "::endgroup::"
           echo "::group::Run pip install .[test,pretty${{ matrix.extra }}] codecov flake8"
           pip install .[test,pretty${{ matrix.extra }}] codecov flake8
-          echo ::endgroup::
+          echo "::endgroup::"
       - name: Run tests with ${{ matrix.args }}
         run: python run-tests.py ${{ matrix.args }}
       - name: Upload test coverage
@@ -79,17 +79,17 @@ jobs:
         run: |
           echo "::group::Run try-treedb.py"; FAILED=0;
           python try-treedb.py || FAILED=$?
-          echo ::endgroup::
+          echo "::endgroup::"
           [ $FAILED -eq 0 ] || echo "::warning::try-treedb.py failed with exit code $FAILED"
         shell: bash
       - name: Run lint-code.py (if -lint)
         if: ${{ contains(matrix.name, '-lint') }}
         run: |
-          echo ::group::Run lint-code.py --version
+          echo "::group::Run lint-code.py --version"
           echo "$(python lint-code.py --version)"
-          echo ::endgroup::
-          echo ::group::Run lint-code.py; FAILED=0; python lint-code.py || FAILED=$?; echo ::endgroup::
-          [ $FAILED -eq 0 ] || echo ::warning::lint-code.py failed with exit code $FAILED
+          echo "::endgroup::"
+          echo "::group::Run lint-code.py"; FAILED=0; python lint-code.py || FAILED=$?; echo "::endgroup::"
+          [ $FAILED -eq 0 ] || echo "::warning::lint-code.py failed with exit code $FAILED"
         shell: bash
       - name: Upload ${{ matrix.name }} artifacts
         uses: actions/upload-artifact@v2
